name: Banking DWH CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                pip install pandas faker

            - name: Generate test data
              run: |
                python data/simulator/generate_data.py
            
            - name: Run data quality tests
              run: |
                python tests/test_data_quality.py